version: '3.8'

services:
  baby-tracking:
    # Verwende das Image von Docker Hub
    image: sleepwalker86/myBaby:v1.0.0
    # Oder baue lokal: build: .
    container_name: baby-tracking
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    environment:
      - DATABASE_PATH=/data/baby_tracking.db
      - PORT=8000
    restart: unless-stopped

